/*
* Distributed Algebraic Computations
* Copyright (C) 2019  Patrik Omland
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*
* This program was generated by DAC "Distributed Algebraic Computations"
* The source code for the generator is available on GitHub
* https://github.com/siquus/dac
*/


#include <stdint.h>
#include <stddef.h>
#include <linux/types.h>
#include <pthread.h>


#include "error_functions.h"

#include "InstructionsSolarSystem.h"

#include "DacSolarSystem.h"




/* Exported Functions ******************************************************************************/


/* The main run routine ****************************************************************************/
int DacSolarSystemRun(size_t threadsNrOf)
{
	void * instance = NULL;
	StartThreads(&instance, threadsNrOf, &jobPoolInitSolarSystem);
	JoinThreads(instance);

	return 0;
}

