/*
* Distributed Algebraic Computations
* Copyright (C) 2019  Patrik Omland
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*
* This program was generated by DAC "Distributed Algebraic Computations"
* The source code for the generator is available on GitHub
* https://github.com/siquus/dac
*/


#include <stdint.h>
#include <stddef.h>
#include <linux/types.h>
#include <pthread.h>


#include "error_functions.h"

#include "InstructionsTest.h"

#include "DacTest.h"


DacOutputCallbackmatrixProd_t DacOutputCallbackmatrixProd = NULL;
DacOutputCallbackmatrixKronProd_t DacOutputCallbackmatrixKronProd = NULL;
DacOutputCallbackProduct_t DacOutputCallbackProduct = NULL;
DacOutputCallbackSum_t DacOutputCallbackSum = NULL;
DacOutputCallbackSmallerThan_t DacOutputCallbackSmallerThan = NULL;
DacOutputCallbackWhile_t DacOutputCallbackWhile = NULL;


/* Exported Functions ******************************************************************************/
void DacOutputCallbackmatrixProd_Register(DacOutputCallbackmatrixProd_t callback)
{
	 DacOutputCallbackmatrixProd = callback;
}

void DacOutputCallbackmatrixKronProd_Register(DacOutputCallbackmatrixKronProd_t callback)
{
	 DacOutputCallbackmatrixKronProd = callback;
}

void DacOutputCallbackProduct_Register(DacOutputCallbackProduct_t callback)
{
	 DacOutputCallbackProduct = callback;
}

void DacOutputCallbackSum_Register(DacOutputCallbackSum_t callback)
{
	 DacOutputCallbackSum = callback;
}

void DacOutputCallbackSmallerThan_Register(DacOutputCallbackSmallerThan_t callback)
{
	 DacOutputCallbackSmallerThan = callback;
}

void DacOutputCallbackWhile_Register(DacOutputCallbackWhile_t callback)
{
	 DacOutputCallbackWhile = callback;
}



/* The main run routine ****************************************************************************/
int DacRun(size_t threadsNrOf)
{
	if(NULL == DacOutputCallbackmatrixProd)
	{
		fatal("DacOutputCallbackmatrixProd == NULL");
	}

	if(NULL == DacOutputCallbackmatrixKronProd)
	{
		fatal("DacOutputCallbackmatrixKronProd == NULL");
	}

	if(NULL == DacOutputCallbackProduct)
	{
		fatal("DacOutputCallbackProduct == NULL");
	}

	if(NULL == DacOutputCallbackSum)
	{
		fatal("DacOutputCallbackSum == NULL");
	}

	if(NULL == DacOutputCallbackSmallerThan)
	{
		fatal("DacOutputCallbackSmallerThan == NULL");
	}

	if(NULL == DacOutputCallbackWhile)
	{
		fatal("DacOutputCallbackWhile == NULL");
	}

	void * instance = NULL;
	StartThreads(&instance, threadsNrOf, &jobPoolInitTest);
	JoinThreads(instance);

	return 0;
}

